from oh_my_subagents.product_identity import LEGACY_BANKSIA_IDENTITY, OMS_IDENTITY


def test_oms_identity_is_canonical_and_legacy_identity_is_exact() -> None:
    assert OMS_IDENTITY.distribution_name == "oh-my-subagents"
    assert OMS_IDENTITY.import_package == "oh_my_subagents"
    assert OMS_IDENTITY.application_name == "oh-my-subagents"
    assert OMS_IDENTITY.database_filename == "oms.persistence"
    assert OMS_IDENTITY.postgres_schema == "oms"
    assert OMS_IDENTITY.provider_environment_filename == "oms.env"
    assert OMS_IDENTITY.task_container_name == ".oms"
    assert OMS_IDENTITY.system_prompt_root == "oms_system"
    assert OMS_IDENTITY.dispatch_request_root == "oms_dispatch_request"
    assert OMS_IDENTITY.node_mcp_server_name == "oms_node"
    assert OMS_IDENTITY.node_mcp_transport_name == "oms-node-managed"
    assert OMS_IDENTITY.operator_mcp_server_name == "oms_operator"
    assert OMS_IDENTITY.systemd_service_name == "oh-my-subagents.service"
    assert OMS_IDENTITY.launchd_service_name == "io.github.ringlochid.oh-my-subagents"
    assert OMS_IDENTITY.scheduled_task_service_name == r"\Oh My Subagents\Controller"
    assert OMS_IDENTITY.service_logger_name == "oh_my_subagents.service"

    assert LEGACY_BANKSIA_IDENTITY.distribution_name == "banksia"
    assert LEGACY_BANKSIA_IDENTITY.import_package == "banksia"
    assert LEGACY_BANKSIA_IDENTITY.application_name == "banksia"
    assert LEGACY_BANKSIA_IDENTITY.database_filename == "banksia.persistence"
    assert LEGACY_BANKSIA_IDENTITY.postgres_schema == "banksia"
    assert LEGACY_BANKSIA_IDENTITY.provider_environment_filename == "banksia.env"
    assert LEGACY_BANKSIA_IDENTITY.task_container_name == ".banksia"
    assert LEGACY_BANKSIA_IDENTITY.system_prompt_root == "banksia_system"
    assert LEGACY_BANKSIA_IDENTITY.dispatch_request_root == "banksia_dispatch_request"
    assert LEGACY_BANKSIA_IDENTITY.node_mcp_server_name == "banksia_node"
    assert LEGACY_BANKSIA_IDENTITY.node_mcp_transport_name == "banksia-node-managed"
    assert LEGACY_BANKSIA_IDENTITY.operator_mcp_server_name == "banksia_operator"
    assert LEGACY_BANKSIA_IDENTITY.systemd_service_name == "banksia.service"
    assert LEGACY_BANKSIA_IDENTITY.launchd_service_name == "io.github.ringlochid.banksia"
    assert LEGACY_BANKSIA_IDENTITY.scheduled_task_service_name == r"\Banksia\Controller"
    assert LEGACY_BANKSIA_IDENTITY.service_logger_name == "banksia.service"
